# Generated by Django 4.2.2 on 2023-07-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctordeatails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='product_images')),
                ('description', models.CharField(max_length=100)),
                ('fees', models.IntegerField()),
            ],
        ),
    ]
